language: node_js
node_js: 
  - 13

services:
  - docker 

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script: 
  - docker --version 
  # - docker build -t udagram-api-feed .
  # - docker build -t udagram-frontend .
  # - docker build -t udagram-api-user .
  # - docker build -t udagram-reverseproxy .
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed alliwene/udagram-api-feed:latest
  - docker tag udagram-frontend alliwene/udagram-frontend:latest
  - docker tag udagram-api-user alliwene/udagram-api-user:latest
  - docker tag reverseproxy alliwene/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alliwene/udagram-api-feed:latest
  - docker push alliwene/udagram-frontend:latest
  - docker push alliwene/udagram-api-user:latest
  - docker push alliwene/reverseproxy:latest  
